name: Daily pipeline 

on:
  workflow_dispatch: {}
  schedule:
    - cron: '25 13 * * 0-4'

jobs:
  generate_and_send_digest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: List Directory Contents
      run: |
        ls -R
    - name: Generate Digest 
      run: |
        python src/actions.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
    - name: Commit and Push
      run: |
        # Configure git
        git config --local user.email "hmanickam13@gmail.com"
        git config --local user.name "hmanickam13"
  
        # Check for changes and commit if necessary
        git add src/dbs/rss_sum.db docs/
        # git add -A
        git diff-index --quiet HEAD || git commit -m "update db & docs" && git push